### ISSUE TITLE
[Wiki] Documentação das rotas e das tabelas criadas na api

### ISSUE THREAD

**Issue by FelipeRubelBorges** [PrisonGO/PrisonWiki#1]

**Comment by willedouglas** [comment]
Realizado a criação do arquivo de diagramação das classes UML. Aguardando receber as rotas do Eduardo para poder documentar as rotas para as tabelas criadas e finalizar a issue.

**Comment by willedouglas** [comment]
Realizada documentação das rotas. Arquivo disponível em Rotas.md.
