### ISSUE TITLE
[WIKI] Ajustar a tabela de regras na UML

### ISSUE THREAD

**Issue by raphaelvitorino** [PrisonGO/PrisonWiki#7]
Os campos da tabela de detentos estão incompletos, é necessário adicionar todos os campos que foram implementados na API. Segue abaixo os campos utilizados no GET do detento:
{  prisioners
  "id": 1,
  "name": "Teste Teste",
  "birth": "1960-10-16",
  "dad": "Teste Pai",
  "mother": "Teste Mae",
  "process_number": "0000001",
  "information_criminal": "Teste 123",
  "risk_prisioner": null,
  "aliases": [],
  "documents": [],
  "telephones": []
}

**Comment by eduardobarbiero** [comment]
Feito.
